version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: oop-portal
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oop-portal.rule=Host(`oop.prstart.hu`)"
      - "traefik.http.routers.oop-portal.entrypoints=websecure"
      - "traefik.http.routers.oop-portal.tls.certresolver=myresolver"
    networks:
      - traefik

networks:
  traefik:
    external: true
